### ISSUE TITLE
DockerFile doesn't work

### ISSUE THREAD

**Issue by TheDevFreak** [sn0w/magisafe#1]
When building the docker file and then running a container with it this is thrown into the `docker logs`

```
yarn install v1.0.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
info Lockfile not saved, no dependencies.
Done in 0.04s.
module.js:473
      throw err;
      ^

Error: Cannot find module '/data/magisafe.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

```

**Comment by sn0w** [comment]
That's because the dockerfile is designed to be used with `docker-compose`.
If you don't want that you'll have to mount with docker's `-v` flag.

![](https://cdn.lks.li/koh04KQdTj.png)

**Comment by TheDevFreak** [comment]
Ah, my bad sorry.

**Comment by TheDevFreak** [comment]
@sn0w this may come off as a bit annoying, but i've just used docker compose instead, `docker-compose build` aaand when i run with `docker run -d -p 9999:9999 magisafe_safe` same error. also same error if i use `-v /data` too

**Comment by sn0w** [comment]
yup. Also docker-compose is not just for building.
It's also for organizing and linking the containers.

You might want to take a look at https://docs.docker.com/compose/overview/
